### ISSUE TITLE
Subir a la wiki 1 documento de Python

### ISSUE THREAD

**Issue by JoaquinZabala** [CodeSystem2022/Grupo_Programaci-nUTN-TercerSemestre#15]

**Comment by NahuelAlaniz** [comment]
Lista de algunos comandos básicos en Python:
print(): Imprime un mensaje o valor en la consola.
input(): Recibe una entrada del usuario desde la consola.
if, else, elif: Estructuras de control condicional para tomar decisiones basadas en condiciones.
for: Estructura de control de bucle que itera sobre una secuencia o una colección de elementos.
while: Estructura de control de bucle que se repite mientras se cumpla una condición.
def: Define una función.
return: Devuelve un valor desde una función.
import: Importa un módulo o una biblioteca para utilizar en el programa.
len(): Devuelve la longitud (número de elementos) de una secuencia o colección.
range(): Genera una secuencia de números.
Operadores matemáticos: + (suma), - (resta), * (multiplicación), / (división), % (módulo), ** (potencia).
Operadores de comparación: == (igual), != (no igual), < (menor que), > (mayor que), <= (menor o igual que), >= (mayor o igual que).
Operadores lógicos: and (y lógico), or (o lógico), not (negación lógica).
Estos son solo algunos de los comandos básicos en Python. Hay muchos más que se pueden utilizar para diferentes propósitos, como trabajar con listas, diccionarios, archivos, manipulación de cadenas, entre otros.

**Comment by CamilaGonzalez97** [comment]
¿QUÉ ES PYTHON Y PARA QUE SIRVE? 
Python es un lenguaje de programación de propósito general que se ejecuta en casi todas las arquitecturas de sistemas y se puede utilizar para una amplia gama de aplicaciones en diferentes campos, desde el desarrollo web hasta el aprendizaje automático. Es un lenguaje de código abierto administrado por Python Software Foundation, una corporación sin fines de lucro que posee propiedad intelectual relacionada con Python. Las personas pueden usar y distribuir el código fuente del mismo de forma gratuita, incluso con fines comerciales.
Python es un lenguaje fácil de aprender y usar. Es muy popular entre los programadores principiantes y experimentados debido a su sintaxis clara y legible. Además, Python tiene una gran cantidad de bibliotecas y marcos que facilitan la creación de aplicaciones.
