### ISSUE TITLE
Subir a la wiki 1 documento de JavaScript

### ISSUE THREAD

**Issue by JoaquinZabala** [CodeSystem2022/Grupo_Programaci-nUTN-TercerSemestre#22]

**Comment by NadiaCruz1** [comment]
### **¿Qué es JavaScript?¿Cuál es su función?**
JavaScript es un lenguaje de programación versátil y poderoso que se utiliza para agregar interactividad, manipular el contenido de las páginas web y desarrollar aplicaciones web completas tanto en el lado del cliente como en el lado del servidor. Su flexibilidad y amplia adopción lo optimizan en una herramienta fundamental en el desarrollo web moderno.

El funcionamiento de JavaScript puede resumirse en los siguientes puntos:

1. Incorporación en páginas web: JavaScript se incorpora en páginas web mediante etiquetas <script>, que se colocan en el código HTML. Puede estar en el encabezado ** <head>**o en el cuerpo** <body>**del documento HTML. También se puede utilizar en archivos JavaScript separados y enlazarse a la página web.
2. Interacción con el DOM: El Document Object Model (DOM) es una representación estructurada del contenido de una página web. JavaScript puede acceder y manipular el DOM para realizar acciones como cambiar el contenido de un elemento, modificar estilos, agregar o eliminar elementos, y responder a eventos como clics de botón o envío de formularios.
3. Manipulación de datos: JavaScript permite crear variables para almacenar datos y realizar operaciones matemáticas, manejo de cadenas de texto, manejo de fechas y estructuras de datos como arreglos y objetos.
4. Funciones y eventos: JavaScript permite definir y ejecutar funciones, que son bloques de código reutilizables. También puede responder a eventos, como clics de botón, movimientos del ratón o cargas de página, mediante funciones de manejo de eventos.
5. Comunicación con el servidor: JavaScript puede comunicarse con el servidor web utilizando tecnologías para enviar y recibir datos de manera asíncrona, sin tener que recargar la página completa.
6. Bibliotecas y frameworks: Existen numerosas bibliotecas y frameworks de JavaScript que tienen conjuntos de herramientas y funcionalidades adicionales para facilitar el desarrollo web y la construcción de aplicaciones más complejas.
