### ISSUE TITLE
Crear Wiki-Flutter

### ISSUE THREAD

**Issue by CamilaGonzalez97** [CodeSystem2022/Grupo_Programaci-nUTN-TercerSemestre#36]
¿Qué es y para qué sirve?
¿Como funciona?

**Comment by JoaquinZabala** [comment]
Trabajo terminado y subido a la wiki , Flutter!

![image](https://github.com/CodeSystem2022/Grupo_Programaci-nUTN-TercerSemestre/assets/111473041/ac17a8db-c637-4bbe-a018-013bad6eb0c4)
